# Request 
---
# Response
bool success                  
string message                # 說明訊息

# 目標點的座標 (相對於機器人當前位置，已根據牆面校正)
# +y 是正前方, +x 是正右方
float64 target_x              
float64 target_y

# 機器人到達目標點後，最終需要面向的角度 (弧度)
# 0 表示面向正前方 (與牆面平行)
float64 target_final_yaw
