# Request
float64 target_front_distance
float64 target_rear_distance
float64 target_left_distance
float64 target_right_distance
float64 target_angle
string align_to_wall
bool use_odometry

---
# Response
bool success
string message

